services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      REDIS_HOST: ${REDIS_HOST}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      SECURE_SSL_REDIRECT: ${SECURE_SSL_REDIRECT:-false}
      TEST_USER_PASSWORD: ${TEST_USER_PASSWORD:-}
    volumes:
      - media_files:/app/mediafiles

volumes:
  media_files:
