# Generated by Django 5.2.12 on 2026-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_last_empty_at_server_room_server_servermember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='server_avatars/'),
        ),
    ]
