# Generated by Django 5.2.12 on 2026-04-20 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roomchatmessage_updated_at_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['server', '-created_at'], name='chat_server_created_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['server', 'is_active'], name='room_server_active_idx'),
        ),
        migrations.AddIndex(
            model_name='roomchatmessage',
            index=models.Index(fields=['room', '-created_at'], name='roomchat_room_created_idx'),
        ),
    ]
